version: '3.9'
services:
  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_user_password
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: python_app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: your_db_name
      DB_USER: your_db_user
      DB_PASSWORD: your_user_password
      AMOUNT_OF_ROWS: 3000
    depends_on:
      - db
    command: python main.py

volumes:
  db_data:
